//Console.WriteLine("Hello, World!");
//HelloWord.Run();
//HelloWordWithComments.Run();
//Variables.Run();
//DataTypes.Run();
//StringInterpolation.Run();
//TypeConversion.Run();
//InputOutput.Run();
//ArithmeticOperations.Run();
//ComparisonOperations.Run();
//LogicOperations.Run();
//BasicOperationsPractices.Question2.Run();
//BasicOperationsPractices.Question3.Run();
//BasicOperationsPractices.Question4.Run();
BasicOperationsPractices.Question5.Run();