//Console.WriteLine("Hello, World!");
//HelloWord.Run();
//HelloWordWithComments.Run();
//Variables.Run();
//DataTypes.Run();
//StringInterpolation.Run();
//TypeConversion.Run();
//InputOutput.Run();
//ArithmeticOperations.Run();
//ComparisonOperations.Run();
//LogicOperations.Run();
//BasicOperationsPractices.Question2.Run();
//BasicOperationsPractices.Question3.Run();
//BasicOperationsPractices.Question4.Run();
//BasicOperationsPractices.Question5.Run();
//BasicOperationsPractices.Question06.Run();
//BasicOperationsPractices.Question07.Run();
//BasicOperationsPractices.Question08.Run();
//BasicOperationsPractices.Question09.Run();
//BasicOperationsPractices.Question10.Run();
//BasicOperationsPractices.Question11.Run();
//BasicOperationsPractices.Question12.Run();
//BasicOperationsPractices.Question13.Run();
//BasicOperationsPractices.Question14.Run();
//BasicOperationsPractices.Question15.Run();
//BasicOperationsPractices.Question16.Run();
//SelectionPractices.Question01.Run();
//SelectionPractices.Question02.Run();
//SelectionPractices.Question03.Run();
//SelectionPractices.Question04.Run();
//SelectionPractices.Question05.Run();
//SelectionPractices.Question06.Run();
//SelectionPractices.Question07.Run();
//SelectionPractices.Question08.Run();
//SelectionPractices.Question09.Run();
//SelectionPractices.Question10.Run();
//SelectionPractices.Question11.Run();
//SelectionPractices.Question12.Run();
SelectionPractices.Question13.Run();



